L.PX/Controllers/LeilaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using L.PX.Core;
using L.PX.Core.Data;
using System.Web.Security;


namespace L.PX.Controllers
{
    public class LeilaoController : Controller
    {
        static LpxDao leilaoDB = new LpxDao();
        Leilao leilao = leilaoDB.Leiloes.First();

        //
        // GET: /Leilao/

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");


            var email = Membership.GetUser().Email;
            var usuario = leilaoDB.Users.Single(u => u.Email == email);

            var participante = leilao.FindParticipante(usuario);

            if ((participante != null) && (participante.IsContratante == false))
            {
                return RedirectToAction("TelaParticipante");
            }

            if ((participante != null) && (participante.IsContratante == true))
            {
                return RedirectToAction("TelaContratante");
            }

            return View();
        }


        //
        // GET: /Gerenciar Leilao/

        public ActionResult GerenciarLeilao()
        {

            var email = Membership.GetUser().Email;
            var usuario = leilaoDB.Users.Single(u => u.Email == email);

            var participante = leilao.FindParticipante(usuario);

            if ((participante != null) && (participante.IsContratante == true))
                return RedirectToAction("TelaGerenciador");
            else
                return RedirectToAction("TelaGerenciadorPart");

            return View();

        }


        //GET: TelaParticipante/
        public ActionResult TelaParticipante()
        {
            var email = Membership.GetUser().Email;
            var usuario = leilaoDB.Users.Single(u => u.Email == email);
            var lance = Lance.Build(10, leilao.NumeroDeLotes, usuario);

            ViewBag.Lances = leilao.ListaLancesDosUsuarios().Where(l => l.Lance.User == usuario);
            return View(lance);
        }

        [HttpPost]
        public ActionResult TelaParticipante(Lance lance)
        {
            TryUpdateModel(lance);

            var email = Membership.GetUser().Email;
            var usuario = leilaoDB.Users.Single(u => u.Email == email);
            lance.User = usuario;
            var lanceProcessado = leilao.RecebeLance(lance);

            ViewBag.Lances = leilao.ListaLancesDosUsuarios().Where(l => l.Lance.User == usuario);
            return View();
        }




        //Get: TelaContratante/
        public ActionResult TelaContratante()
        {
            ViewBag.Participantes = leilaoDB.Participantes.Include("Usuario").Where(p => p.Leilao.Id == leilao.Id);
            return View(leilao);
        }

        [HttpPost]
        public ActionResult TelaContratante(Lance lance)
        {
            if (Membership.GetUser(User.Identity.Name).IsOnline == true)
                lance.User.Estado = "Online";
            else
                lance.User.Estado = "Offline";
            return View();
        }


        //Get: TelaGerenciador/
        public ActionResult TelaGerenciador()
        {

            return View();

        }

        [HttpPost]
        public ActionResult TelaGerenciador(Leilao leilao)
        {
            if (ModelState.IsValid)
            {
                leilaoDB.Leiloes.Add(leilao);
                leilaoDB.SaveChanges();
                return RedirectToAction("TelaGerenciador");
            }
            return View(leilao);
        }

        //Get: TelaGerenciadorPart/
        public ActionResult TelaGerenciadorPart()
        {
            ViewBag.Participantes = leilaoDB.Participantes.Include("Usuario").Where(p => p.Leilao.Id == leilao.Id);
            return View(leilao);
        }

        [HttpPost]
        public ActionResult TelaGerenciadorPart(Leilao leilao)
        {
            return RedirectToAction("TelaParticipante");
            return View(leilao);
        }

        //Get: TelaAddParticipante/
        public ActionResult TelaAddParticipante()
        {
            ViewBag.Participantes = new SelectList(leilaoDB.Participantes, "Participantes", "Email"); ;
            return View(); 
        }



    }
}

L.PX/Views/Leilao/Cronometer.cshtml
@{
    ViewBag.Title = "Cronometer";
}

<div id="timelabel"></div>
<script type="text/javascript">
var leave= <%=seconds%>;

CounterTimer();
var interv=setInterval(ConterTime,1000);

function ConterTimer()
{
    var day = Math.floor(leave/(60*60*24));
    var hour = Math.floor(leave/3600)-(day * 24); 
    var minute = Math.floor(leave/60)-(day * 24* 60)-(hour *60);
    var second = Math.floor(leave)-(day * 24 * 60 * 60) - (hour * 60 * 60)- (minute * 60);

    hour = hour<10 ? "0" + hour : hour;
    minute = minute<10 ? "0" + minute : minute;
    second = second<10 ? "0" + second : second;

    var remain= day + "days"+ hour+":"+ minute + ":" +second ;
    leave = leave-1;

    document.getElementById("timelabel").innerHTML=remain;
}




</script>

L.PX/Views/Leilao/GerenciadordeConvites.cshtml
@model L.PX.Core.Leilao

@{
    ViewBag.Title = "GerenciadordeConvites";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Novo Leilão</h2>
<fieldset>
    <legend>Leilao</legend>
    <div class="display-label">
        @Html.Label("Mensagem")  </div>
    <div class="display-field">
        @Html.TextArea("Mensagem")</div>
    </fieldset>

    
<ul id="navlist">
                <li><a href="@Url.Content("~/TelaAddParticipante/")">Adicionar Participante</a></li>
             </ul>        

L.PX/Views/Leilao/TelaAddParticipante.cshtml
@model IEnumerable<L.PX.Models.LeilaoModelContext>
@{
    ViewBag.Title = "TelaAddParticipante";
}

<h2>Adicionar Participante</h2>


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>



@using (Html.BeginForm()) {
    
        <fieldset>
        <legend>Participante</legend>
        <p>Entre com o Email do novo participante do leilão </p>
        <div class="editor-label">
                @Html.LabelFor(m => m.Email)
            </div>
           <div class="editor-field">
                 @Html.DropDownList("Participantes", String.Empty)
                 @Html.ValidationMessageFor(model => model.Email )
        </div>
        </fieldset>
    <input type="submit" value="Mais" /> 
    <input type="submit" value="Enviar" />
    
}

L.PX/Views/Leilao/TelaContratante.cshtml
@model L.PX.Core.Leilao
@{
    ViewBag.Title = "TelaContratante";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    TelaContratante</h2>
<fieldset>
    <legend>Leilao</legend>
    <div class="display-label">
        Valor atual</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ValorAtual)
    </div>
    <div class="display-label">
        Número de lotes</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumeroDeLotes)
    </div>
    <div class="display-label">
        Valor inicial</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ValorInicial)
    </div>
</fieldset>
<fieldset>
    <legend>Lances</legend>
    @foreach (var item in Model.ListaLancesDosUsuarios())
    {
        <table>
            <tr>@item.Valor.ToString() - @item.Lance.User.NomeCompleto.ToString()</tr>
        </table>
    }
</fieldset>
<fieldset>
    <legend>Participantes</legend>
    @foreach (L.PX.Core.Participante item in ViewBag.Participantes)
    {
        <table>
            <tr>@item.Usuario.Email.ToString() - @item.Usuario.Estado.ToString()</tr>
        </table>
    }
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<li>@Html.ActionLink("Gerenciar Leilão","GerenciarLeilao","Leilao")</li>

L.PX/Views/Leilao/TelaGerenciador.cshtml
@model L.PX.Core.Leilao
@{
    ViewBag.Title = "TelaGerenciador";
}
<h2> 
    TelaGerenciador</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{

    <h3>
        Contratante</h3>
    
    <fieldset>
        <legend>Leilões cadastrados</legend>
    </fieldset>
    <br />

    
    <fieldset>
        <legend>Dados do Novo Leilão</legend>
        <div class="display-label">
            Valor inicial</div>
        <div class="editor-label">
            @Html.EditorFor(model => model.ValorInicial)
            @Html.ValidationMessageFor(model => model.ValorInicial)</div>
        <div class="display-label">
            Número de lotes</div>
        <div class="editor-label">
            @Html.EditorFor(model => model.NumeroDeLotes)
            @Html.ValidationMessageFor(model => model.NumeroDeLotes)</div>
        <br />
    </fieldset>
    <br />
   
    <input type="submit" value="Criar" />
    
}

L.PX/Views/Leilao/TelaGerenciadorPart.cshtml
@model L.PX.Core.Leilao
@{
    ViewBag.Title = "TelaGerenciadorPart";
}
<h2>
    TelaGerenciadorPart</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{

    <h3>
        Participante</h3>
    <fieldset>
        <legend>Dados do Leilão</legend>
        <div class="display-label">
            Identificador</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Id)</div>
        <div class="display-label">
            Valor inicial</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ValorInicial)</div>
        <div class="display-label">
            Número de lotes</div>
        <div class="display-field">
            @Html.DisplayFor(model => model.NumeroDeLotes)
            <br />
    </fieldset>
    <br />
   
    <input type="submit" value="Voltar" />
    
}

L.PX/Views/Leilao/TelaParticipante.cshtml
@model L.PX.Core.Lance
@{
    ViewBag.Title = "Efetuar lance";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@{ var lances = ViewBag.Lances; }

@using (Html.BeginForm())
{

    <h1>
        Participante</h1>
    <fieldset>
        <legend>Seu lance</legend>
        <div class="editor-label">
            @Html.Label("Incremento")
        </div>
        <div class="editor-field">
            @Html.TextBox("Incremento")
        </div>
        <div class="editor-label">
            @Html.Label("Número de lotes")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(l => l.NumeroDeLotes)
        </div>
    </fieldset>
   
    
    <input type="submit" value="OK" />
    <fieldset>
    <legend>Historico de lances</legend>
    @foreach (L.PX.Core.LanceProcessado lance in lances)
    {
        @lance.ToString()
        <br />  
    }
    </fieldset>

}